# Generated by Django 2.2.10 on 2020-02-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.BigIntegerField()),
            ],
        ),
    ]
