# Generated by Django 2.2.10 on 2020-02-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_aa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='aa',
        ),
    ]
