# Generated by Django 2.2.10 on 2020-03-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
